export interface Skill {
  name: string;
}

export const skills: Skill[] = [
  { name: 'Communication' },
  { name: 'Teamwork' },
  { name: 'Problem-solving' },
  { name: 'Time management' },
  { name: 'Leadership' },
  { name: 'Adaptability' },
  { name: 'Creativity' },
  { name: 'Emotional intelligence' },
  { name: 'Critical thinking' },
  { name: 'Conflict resolution' },
  { name: 'Decision-making' },
  { name: 'Work ethic' },
  { name: 'Active listening' },
  { name: 'Stress management' },
  { name: 'Collaboration' },
  { name: 'Negotiation' },
  { name: 'Empathy' },
  { name: 'Self-motivation' },
  { name: 'Flexibility' },
  { name: 'Patience' },
  { name: 'Open-mindedness' },
  { name: 'Self-awareness' },
  { name: 'Persuasion' },
  { name: 'Public speaking' },
  { name: 'Networking' },
  { name: 'Mentoring' },
  { name: 'Delegation' },
  { name: 'Cultural awareness' },
  { name: 'Positive attitude' },
  { name: 'Resilience' },
  { name: 'Humility' },
  { name: 'Confidence' },
  { name: 'Integrity' },
  { name: 'Accountability' },
  { name: 'Dependability' },
  { name: 'Work-life balance' },
  { name: 'Self-regulation' },
  { name: 'Resourcefulness' },
  { name: 'Goal setting' },
  { name: 'Stress resistance' },
  { name: 'Project management' },
  { name: 'Data analysis' },
  { name: 'Programming' },
  { name: 'Graphic design' },
  { name: 'Foreign languages' },
  { name: 'Digital marketing' },
  { name: 'SEO' },
  { name: 'Content writing' },
  { name: 'Copywriting' },
  { name: 'Public relations' },
  { name: 'Accounting' },
  { name: 'Financial analysis' },
  { name: 'Sales' },
  { name: 'Customer service' },
  { name: 'Software development' },
  { name: 'Web development' },
  { name: 'Database management' },
  { name: 'Cloud computing' },
  { name: 'Cybersecurity' },
  { name: 'Network administration' },
  { name: 'Machine learning' },
  { name: 'Artificial intelligence' },
  { name: 'Blockchain' },
  { name: 'UI/UX design' },
  { name: 'Video editing' },
  { name: 'Photography' },
  { name: 'Event planning' },
  { name: 'Legal research' },
  { name: 'Medical coding' },
  { name: 'Data visualization' },
  { name: 'Statistical analysis' },
  { name: 'Business analysis' },
  { name: 'Supply chain management' },
  { name: 'Logistics' },
  { name: 'Manufacturing' },
  { name: 'Quality assurance' },
  { name: 'Technical writing' },
  { name: 'Translation' },
  { name: 'Transcription' },
  { name: 'Teaching' },
  { name: 'Tutoring' },
  { name: 'Coaching' },
  { name: 'Research' },
  { name: 'Editing' },
  { name: 'Proofreading' },
  { name: 'Grant writing' },
  { name: 'Proposal writing' },
  { name: 'Press release writing' },
  { name: 'Content management systems' },
  { name: 'Customer relationship management' },
  { name: 'Enterprise resource planning' },
  { name: 'Human resources management' },
  { name: 'Employee training' },
  { name: 'Recruiting' },
  { name: 'Payroll' },
  { name: 'Benefits administration' },
  { name: 'Labor relations' },
  { name: 'Compensation analysis' },
  { name: 'Organizational development' },
  { name: 'Change management' },
  { name: 'Strategic planning' },
  { name: 'Risk management' },
  { name: 'Compliance' },
  { name: 'Legal compliance' },
  { name: 'Health and safety' },
  { name: 'Environmental management' },
  { name: 'Sustainability' },
  { name: 'Corporate social responsibility' },
  { name: 'Public policy' },
  { name: 'Lobbying' },
  { name: 'Advocacy' },
  { name: 'Community outreach' },
  { name: 'Fundraising' },
  { name: 'Grant administration' },
  { name: 'Nonprofit management' },
  { name: 'Volunteer coordination' },
  { name: 'Philanthropy' },
  { name: 'Donor relations' },
  { name: 'Event coordination' },
  { name: 'Catering' },
  { name: 'Venue management' },
  { name: 'Ticketing' },
  { name: 'Security management' },
  { name: 'Transportation management' },
  { name: 'Hospitality' },
  { name: 'Tourism' },
  { name: 'Travel planning' },
  { name: 'Destination marketing' },
  { name: 'Tour guiding' },
  { name: 'Language proficiency' },
  { name: 'Sign language' },
  { name: 'Braille' },
  { name: 'Speech therapy' },
  { name: 'Occupational therapy' },
  { name: 'Physical therapy' },
  { name: 'Nursing' },
  { name: 'Medical assisting' },
  { name: 'Pharmacy' },
  { name: 'Dentistry' },
  { name: 'Veterinary medicine' },
  { name: 'Public health' },
  { name: 'Epidemiology' },
  { name: 'Nutrition' },
  { name: 'Dietetics' },
  { name: 'Health education' },
  { name: 'Health promotion' },
  { name: 'Emergency medical services' },
  { name: 'Firefighting' },
  { name: 'Law enforcement' },
  { name: 'Criminal justice' },
  { name: 'Forensic science' },
  { name: 'Security' },
  { name: 'Military service' },
  { name: 'Intelligence analysis' },
  { name: 'Counterterrorism' },
  { name: 'Diplomacy' },
  { name: 'International relations' },
  { name: 'Foreign service' },
  { name: 'Peacekeeping' },
  { name: 'Humanitarian aid' },
  { name: 'Disaster response' },
  { name: 'Refugee assistance' },
  { name: 'Immigration services' },
  { name: 'Customs enforcement' },
  { name: 'Border security' },
  { name: 'Customs brokerage' },
  { name: 'Import/export' },
  { name: 'Supply chain logistics' },
  { name: 'Freight forwarding' },
  { name: 'Warehousing' },
  { name: 'Inventory management' },
  { name: 'Distribution' },
  { name: 'Procurement' },
  { name: 'Purchasing' },
  { name: 'Sourcing' },
  { name: 'Vendor management' },
  { name: 'Contract negotiation' },
  { name: 'Contract management' },
  { name: 'Legal drafting' },
  { name: 'Litigation support' },
  { name: 'Mediation' },
  { name: 'Arbitration' },
  { name: 'Intellectual property' },
  { name: 'Patent law' },
  { name: 'Trademark law' },
  { name: 'Copyright law' },
  { name: 'Corporate law' },
  { name: 'Criminal law' },
  { name: 'Family law' },
  { name: 'Estate planning' },
  { name: 'Tax law' },
  { name: 'Immigration law' },
  { name: 'Environmental law' },
  { name: 'Health law' },
  { name: 'Real estate law' },
  { name: 'Bankruptcy law' },
  { name: 'Employment law' },
  { name: 'Civil rights law' },
  { name: 'Consumer protection law' },
  { name: 'Antitrust law' },
  { name: 'Securities law' },
  { name: 'International law' },
  { name: 'Human rights law' },
  { name: 'Public interest law' },
  { name: 'Legal research' },
  { name: 'Legal writing' },
  { name: 'Legal analysis' },
  { name: 'Legal compliance' },
  { name: 'Legal ethics' },
  { name: 'Legal technology' },
  { name: 'Legal project management' },
  { name: 'Legal operations' },
  { name: 'Legal marketing' },
  { name: 'Legal sales' },
  { name: 'Legal recruiting' },
  { name: 'Legal education' },
  { name: 'Legal publishing' },
  { name: 'Legal journalism' },
  { name: 'Legal advocacy' },
  { name: 'Legal consulting' },
  { name: 'Legal training' },
  { name: 'Legal translation' },
  { name: 'Legal transcription' },
  { name: 'Legal interpreting' },
  { name: 'Legal document review' },
  { name: 'Legal billing' },
  { name: 'Legal accounting' },
  { name: 'Legal project budgeting' },
  { name: 'Legal project scheduling' },
  { name: 'Legal project reporting' },
  { name: 'Legal project risk management' },
  { name: 'Legal project quality management' },
  { name: 'Legal project resource management' },
  { name: 'Legal project stakeholder management' },
  { name: 'Legal project procurement' },
  { name: 'Legal project communication' },
  { name: 'Legal project documentation' },
  { name: 'Legal project change management' },
  { name: 'Legal project integration management' }
]
