export class JobModel {
  constructor(
    public id: number,
    public title: string,
    public company: string,
    public logo: string,
    public location: string,
    public salary: string,
    public type: string,
    public experience: string,
    public teamSize: string,
    public description: string,
    public requirements: string,
    public benefits: string,
    public posted?: string,
    public applicants?: string
  ) {}
}

export const Jobs: JobModel[] = [
  new JobModel(
    1,
    'Frontend Developer',
    'TechCorp',
    'assets/png/techcorp-logo.png',
    'New York, NY',
    '$4000-5000',
    'Full-time',
    '2+ years',
    '10-20',
    'Develop modern UI components using Angular and maintain frontend codebase.',
    'Angular, TypeScript, HTML, CSS, RxJS',
    'Medical insurance, Flexible hours, Remote work',
    '2 days ago',
    '32'
  ),
  new JobModel(
    2,
    'React Developer',
    'StartupXYZ',
    'assets/png/startup-logo.png',
    'San Francisco, CA',
    '$5000-6000',
    'Full-time',
    '3+ years',
    '5-10',
    'Build scalable web applications using React and modern JavaScript.',
    'React, JavaScript, Node.js, MongoDB',
    'Stock options, Free lunch, Gym membership',
    '1 day ago',
    '18'
  ),
  new JobModel(
    3,
    'Vue.js Developer',
    'WebStudio',
    'assets/png/webstudio-logo.png',
    'Austin, TX',
    '$4500-5500',
    'Contract',
    '1+ years',
    '3-8',
    'Create responsive web interfaces using Vue.js framework.',
    'Vue.js, Vuex, JavaScript, SASS',
    'Flexible schedule, Training budget',
    '3 days ago',
    '25'
  ),
  new JobModel(
    4,
    'Full Stack Developer',
    'BigTech Inc',
    'assets/png/bigtech-logo.png',
    'Seattle, WA',
    '$6000-8000',
    'Full-time',
    '4+ years',
    '20-50',
    'Work on both frontend and backend systems for enterprise applications.',
    'Angular, Node.js, PostgreSQL, Docker',
    'Medical insurance, 401k, Bonus program',
    '1 week ago',
    '67'
  ),
  new JobModel(
    5,
    'UI/UX Developer',
    'DesignFirst',
    'assets/png/designfirst-logo.png',
    'Los Angeles, CA',
    '$4000-4500',
    'Part-time',
    '2+ years',
    '5-15',
    'Transform designs into interactive web experiences.',
    'HTML, CSS, JavaScript, Figma',
    'Creative freedom, Flexible hours',
    '5 days ago',
    '41'
  ),
  new JobModel(
    6,
    'Senior Frontend Engineer',
    'Enterprise Corp',
    'assets/png/enterprise-logo.png',
    'Chicago, IL',
    '$7000-9000',
    'Full-time',
    '5+ years',
    '50+',
    'Lead frontend development for large-scale enterprise applications.',
    'Angular, TypeScript, Micro-frontends, Jenkins',
    'Medical insurance, Pension, Conference budget',
    '2 weeks ago',
    '89'
  )
];
